# Generated by Django 6.0.1 on 2026-01-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='attempt_times',
            field=models.JSONField(default=list, help_text='List of all attempt times in seconds'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Best/Latest time taken in seconds'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_time_spent',
            field=models.IntegerField(default=0, help_text='Total average time in seconds'),
        ),
    ]
