# Generated by Django 6.0.1 on 2026-01-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_userprogress_attempt_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='avatar_url',
            field=models.URLField(default='https://api.dicebear.com/7.x/avataaars/svg?seed=Bunny', help_text="URL to user's avatar"),
        ),
    ]
