# Generated by Django 6.0.1 on 2026-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_userstats_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='userstats',
            name='avatar',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='avatars/'),
        ),
    ]
